# Generated by Django 4.0 on 2021-12-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('sp', 'SPORT'), ('si', 'SIENCE'), ('ec', 'ECONOMIC'), ('po', 'POLITIC'), ('cu', 'CULTURAL')], help_text='موضوع موردنظر خود را انتخاب نمایید', max_length=2, verbose_name='موضوع')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام خود را وارد کنید', max_length=40, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='متن سوال را وارد نمایید', verbose_name='سوال')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questocat', to='quiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('iscorrect', models.BooleanField(default=False, verbose_name='جواب صحیح')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswtoQues', to='quiz.question')),
            ],
        ),
    ]
