# Generated by Django 4.0 on 2021-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='iscorrect',
        ),
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.CharField(max_length=1, null=True, verbose_name='select'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('sp', 'SPORT'), ('si', 'SIENCE'), ('ec', 'ECONOMIC'), ('po', 'POLITIC'), ('cu', 'CULTURAL')], help_text='موضوع موردنظر خود را انتخاب نمایید', max_length=2, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(help_text='متن سوال را وارد نمایید', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='نام خود را وارد کنید', max_length=40, verbose_name='name'),
        ),
    ]
