# Generated by Django 4.0 on 2021-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_iscorrect_answer_select_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='istrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='select',
            field=models.CharField(choices=[('A', 'A)'), ('B', 'B)'), ('C', 'C)'), ('D', 'D)')], max_length=1, null=True, verbose_name='select'),
        ),
    ]
