# Generated by Django 4.0 on 2021-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_istrue_alter_answer_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cs1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='cs2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='cs3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='cs4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[('A', 'A)'), ('B', 'B)'), ('C', 'C)'), ('D', 'D)')], max_length=1, null=True, verbose_name='select'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('sp', 'SPORT'), ('si', 'SIENCE'), ('ec', 'ECONOMIC'), ('po', 'POLITIC'), ('cu', 'CULTURAL')], help_text='موضوع موردنظر خود را انتخاب نمایید', max_length=2, null=True, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
