# Generated by Django 4.0 on 2021-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_cs1_question_cs2_question_cs3_question_cs4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cs1',
            field=models.CharField(default=1, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cs2',
            field=models.CharField(default=2, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cs3',
            field=models.CharField(default=3, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='cs4',
            field=models.CharField(default=4, max_length=255, null=True),
        ),
    ]
