# Generated by Django 4.0 on 2021-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_cs1_alter_question_cs2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='point',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='quiz',
            field=models.JSONField(null=True),
        ),
    ]
