# Generated by Django 4.0 on 2021-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_history_point_history_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
